/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tutorial;

public class App {
    public static void main(String[] args) {
        HelloWorldAnonymousClasses myApp = new HelloWorldAnonymousClasses();
        myApp.sayHello();
    }
}
