/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tutorial;

public class App {
    public static void main(String[] args) {
        Test t = new Test();
		Test t2 = new Test();
    }
}
