/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tutorial;

public class App {
    public static void main(String[] args) {
        LambdaScopeTest st = new LambdaScopeTest();
        LambdaScopeTest.FirstLevel fl = st.new FirstLevel();
        fl.methodInFirstLevel(23);
    }
}
